
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '*hX\x7f\x91z=\x96\x9ed\xb8=\xd9\xa2|\xd9'
    
_lr_action_items = {'DIGIT':([0,],[2,]),'LETTER':([0,],[3,]),'$end':([1,2,3,],[0,-1,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'hex_digit':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> hex_digit","S'",1,None,None,None),
  ('hex_digit -> DIGIT','hex_digit',1,'p_hex_digit','sample.py',139),
  ('hex_digit -> LETTER','hex_digit',1,'p_hex_digit','sample.py',140),
  ('hex_digit_plus -> hex_digit','hex_digit_plus',1,'p_hex_digit_plus','sample.py',145),
  ('hex_digit_plus -> hex_digit hex_digit_plus','hex_digit_plus',2,'p_hex_digit_plus','sample.py',146),
  ('hex_scalar_value -> hex_digit_plus','hex_scalar_value',1,'p_hex_scalar_value','sample.py',154),
]
